version: "3.9"
services:
    node:
        build: .
        container_name: node
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
        networks:
            - workout_diary

networks:
    workout_diary:
        driver: bridge
